// Code generated by internal/sliver/rpc/gen. DO NOT EDIT.

package rpc

import (
	"context"
	"time"

	"github.com/bishopfox/sliver/protobuf/clientpb"
	"github.com/bishopfox/sliver/protobuf/commonpb"
	"github.com/bishopfox/sliver/protobuf/rpcpb"
	"github.com/bishopfox/sliver/protobuf/sliverpb"
	"google.golang.org/grpc"
)

type journalDecorator struct {
	next rpcpb.SliverRPCClient
	hook *JournalHook
}

// WrapJournal decorates next with journaling. A nil hook returns next
// unwrapped so capture is strictly opt-in.
func WrapJournal(next rpcpb.SliverRPCClient, hook *JournalHook) rpcpb.SliverRPCClient {
	if hook == nil {
		return next
	}
	return &journalDecorator{next: next, hook: hook}
}

func (d *journalDecorator) GetVersion(ctx context.Context, in *commonpb.Empty, opts ...grpc.CallOption) (*clientpb.Version, error) {
	start := time.Now()
	resp, err := d.next.GetVersion(ctx, in, opts...)
	d.hook.record(ctx, "GetVersion", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) ClientLog(ctx context.Context, opts ...grpc.CallOption) (rpcpb.SliverRPC_ClientLogClient, error) {
	start := time.Now()
	stream, err := d.next.ClientLog(ctx, opts...)
	d.hook.record(ctx, "ClientLog", time.Since(start).Milliseconds(), err)
	return stream, err
}

func (d *journalDecorator) GetOperators(ctx context.Context, in *commonpb.Empty, opts ...grpc.CallOption) (*clientpb.Operators, error) {
	start := time.Now()
	resp, err := d.next.GetOperators(ctx, in, opts...)
	d.hook.record(ctx, "GetOperators", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) Kill(ctx context.Context, in *sliverpb.KillReq, opts ...grpc.CallOption) (*commonpb.Empty, error) {
	start := time.Now()
	resp, err := d.next.Kill(ctx, in, opts...)
	d.hook.record(ctx, "Kill", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) Reconfigure(ctx context.Context, in *sliverpb.ReconfigureReq, opts ...grpc.CallOption) (*sliverpb.Reconfigure, error) {
	start := time.Now()
	resp, err := d.next.Reconfigure(ctx, in, opts...)
	d.hook.record(ctx, "Reconfigure", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) Rename(ctx context.Context, in *clientpb.RenameReq, opts ...grpc.CallOption) (*commonpb.Empty, error) {
	start := time.Now()
	resp, err := d.next.Rename(ctx, in, opts...)
	d.hook.record(ctx, "Rename", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) GetSessions(ctx context.Context, in *commonpb.Empty, opts ...grpc.CallOption) (*clientpb.Sessions, error) {
	start := time.Now()
	resp, err := d.next.GetSessions(ctx, in, opts...)
	d.hook.record(ctx, "GetSessions", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) MonitorStart(ctx context.Context, in *commonpb.Empty, opts ...grpc.CallOption) (*commonpb.Response, error) {
	start := time.Now()
	resp, err := d.next.MonitorStart(ctx, in, opts...)
	d.hook.record(ctx, "MonitorStart", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) MonitorStop(ctx context.Context, in *commonpb.Empty, opts ...grpc.CallOption) (*commonpb.Empty, error) {
	start := time.Now()
	resp, err := d.next.MonitorStop(ctx, in, opts...)
	d.hook.record(ctx, "MonitorStop", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) MonitorListConfig(ctx context.Context, in *commonpb.Empty, opts ...grpc.CallOption) (*clientpb.MonitoringProviders, error) {
	start := time.Now()
	resp, err := d.next.MonitorListConfig(ctx, in, opts...)
	d.hook.record(ctx, "MonitorListConfig", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) MonitorAddConfig(ctx context.Context, in *clientpb.MonitoringProvider, opts ...grpc.CallOption) (*commonpb.Response, error) {
	start := time.Now()
	resp, err := d.next.MonitorAddConfig(ctx, in, opts...)
	d.hook.record(ctx, "MonitorAddConfig", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) MonitorDelConfig(ctx context.Context, in *clientpb.MonitoringProvider, opts ...grpc.CallOption) (*commonpb.Response, error) {
	start := time.Now()
	resp, err := d.next.MonitorDelConfig(ctx, in, opts...)
	d.hook.record(ctx, "MonitorDelConfig", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) StartMTLSListener(ctx context.Context, in *clientpb.MTLSListenerReq, opts ...grpc.CallOption) (*clientpb.ListenerJob, error) {
	start := time.Now()
	resp, err := d.next.StartMTLSListener(ctx, in, opts...)
	d.hook.record(ctx, "StartMTLSListener", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) StartWGListener(ctx context.Context, in *clientpb.WGListenerReq, opts ...grpc.CallOption) (*clientpb.ListenerJob, error) {
	start := time.Now()
	resp, err := d.next.StartWGListener(ctx, in, opts...)
	d.hook.record(ctx, "StartWGListener", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) StartDNSListener(ctx context.Context, in *clientpb.DNSListenerReq, opts ...grpc.CallOption) (*clientpb.ListenerJob, error) {
	start := time.Now()
	resp, err := d.next.StartDNSListener(ctx, in, opts...)
	d.hook.record(ctx, "StartDNSListener", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) StartHTTPSListener(ctx context.Context, in *clientpb.HTTPListenerReq, opts ...grpc.CallOption) (*clientpb.ListenerJob, error) {
	start := time.Now()
	resp, err := d.next.StartHTTPSListener(ctx, in, opts...)
	d.hook.record(ctx, "StartHTTPSListener", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) StartHTTPListener(ctx context.Context, in *clientpb.HTTPListenerReq, opts ...grpc.CallOption) (*clientpb.ListenerJob, error) {
	start := time.Now()
	resp, err := d.next.StartHTTPListener(ctx, in, opts...)
	d.hook.record(ctx, "StartHTTPListener", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) GetBeacons(ctx context.Context, in *commonpb.Empty, opts ...grpc.CallOption) (*clientpb.Beacons, error) {
	start := time.Now()
	resp, err := d.next.GetBeacons(ctx, in, opts...)
	d.hook.record(ctx, "GetBeacons", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) GetBeacon(ctx context.Context, in *clientpb.Beacon, opts ...grpc.CallOption) (*clientpb.Beacon, error) {
	start := time.Now()
	resp, err := d.next.GetBeacon(ctx, in, opts...)
	d.hook.record(ctx, "GetBeacon", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) RmBeacon(ctx context.Context, in *clientpb.Beacon, opts ...grpc.CallOption) (*commonpb.Empty, error) {
	start := time.Now()
	resp, err := d.next.RmBeacon(ctx, in, opts...)
	d.hook.record(ctx, "RmBeacon", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) GetBeaconTasks(ctx context.Context, in *clientpb.Beacon, opts ...grpc.CallOption) (*clientpb.BeaconTasks, error) {
	start := time.Now()
	resp, err := d.next.GetBeaconTasks(ctx, in, opts...)
	d.hook.record(ctx, "GetBeaconTasks", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) GetBeaconTaskContent(ctx context.Context, in *clientpb.BeaconTask, opts ...grpc.CallOption) (*clientpb.BeaconTask, error) {
	start := time.Now()
	resp, err := d.next.GetBeaconTaskContent(ctx, in, opts...)
	d.hook.record(ctx, "GetBeaconTaskContent", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) CancelBeaconTask(ctx context.Context, in *clientpb.BeaconTask, opts ...grpc.CallOption) (*clientpb.BeaconTask, error) {
	start := time.Now()
	resp, err := d.next.CancelBeaconTask(ctx, in, opts...)
	d.hook.record(ctx, "CancelBeaconTask", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) UpdateBeaconIntegrityInformation(ctx context.Context, in *clientpb.BeaconIntegrity, opts ...grpc.CallOption) (*commonpb.Empty, error) {
	start := time.Now()
	resp, err := d.next.UpdateBeaconIntegrityInformation(ctx, in, opts...)
	d.hook.record(ctx, "UpdateBeaconIntegrityInformation", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) GetJobs(ctx context.Context, in *commonpb.Empty, opts ...grpc.CallOption) (*clientpb.Jobs, error) {
	start := time.Now()
	resp, err := d.next.GetJobs(ctx, in, opts...)
	d.hook.record(ctx, "GetJobs", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) KillJob(ctx context.Context, in *clientpb.KillJobReq, opts ...grpc.CallOption) (*clientpb.KillJob, error) {
	start := time.Now()
	resp, err := d.next.KillJob(ctx, in, opts...)
	d.hook.record(ctx, "KillJob", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) RestartJobs(ctx context.Context, in *clientpb.RestartJobReq, opts ...grpc.CallOption) (*commonpb.Empty, error) {
	start := time.Now()
	resp, err := d.next.RestartJobs(ctx, in, opts...)
	d.hook.record(ctx, "RestartJobs", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) StartTCPStagerListener(ctx context.Context, in *clientpb.StagerListenerReq, opts ...grpc.CallOption) (*clientpb.StagerListener, error) {
	start := time.Now()
	resp, err := d.next.StartTCPStagerListener(ctx, in, opts...)
	d.hook.record(ctx, "StartTCPStagerListener", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) LootAdd(ctx context.Context, in *clientpb.Loot, opts ...grpc.CallOption) (*clientpb.Loot, error) {
	start := time.Now()
	resp, err := d.next.LootAdd(ctx, in, opts...)
	d.hook.record(ctx, "LootAdd", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) LootRm(ctx context.Context, in *clientpb.Loot, opts ...grpc.CallOption) (*commonpb.Empty, error) {
	start := time.Now()
	resp, err := d.next.LootRm(ctx, in, opts...)
	d.hook.record(ctx, "LootRm", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) LootUpdate(ctx context.Context, in *clientpb.Loot, opts ...grpc.CallOption) (*clientpb.Loot, error) {
	start := time.Now()
	resp, err := d.next.LootUpdate(ctx, in, opts...)
	d.hook.record(ctx, "LootUpdate", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) LootContent(ctx context.Context, in *clientpb.Loot, opts ...grpc.CallOption) (*clientpb.Loot, error) {
	start := time.Now()
	resp, err := d.next.LootContent(ctx, in, opts...)
	d.hook.record(ctx, "LootContent", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) LootAll(ctx context.Context, in *commonpb.Empty, opts ...grpc.CallOption) (*clientpb.AllLoot, error) {
	start := time.Now()
	resp, err := d.next.LootAll(ctx, in, opts...)
	d.hook.record(ctx, "LootAll", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) Creds(ctx context.Context, in *commonpb.Empty, opts ...grpc.CallOption) (*clientpb.Credentials, error) {
	start := time.Now()
	resp, err := d.next.Creds(ctx, in, opts...)
	d.hook.record(ctx, "Creds", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) CredsAdd(ctx context.Context, in *clientpb.Credentials, opts ...grpc.CallOption) (*commonpb.Empty, error) {
	start := time.Now()
	resp, err := d.next.CredsAdd(ctx, in, opts...)
	d.hook.record(ctx, "CredsAdd", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) CredsRm(ctx context.Context, in *clientpb.Credentials, opts ...grpc.CallOption) (*commonpb.Empty, error) {
	start := time.Now()
	resp, err := d.next.CredsRm(ctx, in, opts...)
	d.hook.record(ctx, "CredsRm", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) CredsUpdate(ctx context.Context, in *clientpb.Credentials, opts ...grpc.CallOption) (*commonpb.Empty, error) {
	start := time.Now()
	resp, err := d.next.CredsUpdate(ctx, in, opts...)
	d.hook.record(ctx, "CredsUpdate", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) GetCredByID(ctx context.Context, in *clientpb.Credential, opts ...grpc.CallOption) (*clientpb.Credential, error) {
	start := time.Now()
	resp, err := d.next.GetCredByID(ctx, in, opts...)
	d.hook.record(ctx, "GetCredByID", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) GetCredsByHashType(ctx context.Context, in *clientpb.Credential, opts ...grpc.CallOption) (*clientpb.Credentials, error) {
	start := time.Now()
	resp, err := d.next.GetCredsByHashType(ctx, in, opts...)
	d.hook.record(ctx, "GetCredsByHashType", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) GetPlaintextCredsByHashType(ctx context.Context, in *clientpb.Credential, opts ...grpc.CallOption) (*clientpb.Credentials, error) {
	start := time.Now()
	resp, err := d.next.GetPlaintextCredsByHashType(ctx, in, opts...)
	d.hook.record(ctx, "GetPlaintextCredsByHashType", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) CredsSniffHashType(ctx context.Context, in *clientpb.Credential, opts ...grpc.CallOption) (*clientpb.Credential, error) {
	start := time.Now()
	resp, err := d.next.CredsSniffHashType(ctx, in, opts...)
	d.hook.record(ctx, "CredsSniffHashType", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) Hosts(ctx context.Context, in *commonpb.Empty, opts ...grpc.CallOption) (*clientpb.AllHosts, error) {
	start := time.Now()
	resp, err := d.next.Hosts(ctx, in, opts...)
	d.hook.record(ctx, "Hosts", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) Host(ctx context.Context, in *clientpb.Host, opts ...grpc.CallOption) (*clientpb.Host, error) {
	start := time.Now()
	resp, err := d.next.Host(ctx, in, opts...)
	d.hook.record(ctx, "Host", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) HostRm(ctx context.Context, in *clientpb.Host, opts ...grpc.CallOption) (*commonpb.Empty, error) {
	start := time.Now()
	resp, err := d.next.HostRm(ctx, in, opts...)
	d.hook.record(ctx, "HostRm", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) HostIOCRm(ctx context.Context, in *clientpb.IOC, opts ...grpc.CallOption) (*commonpb.Empty, error) {
	start := time.Now()
	resp, err := d.next.HostIOCRm(ctx, in, opts...)
	d.hook.record(ctx, "HostIOCRm", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) Generate(ctx context.Context, in *clientpb.GenerateReq, opts ...grpc.CallOption) (*clientpb.Generate, error) {
	start := time.Now()
	resp, err := d.next.Generate(ctx, in, opts...)
	d.hook.record(ctx, "Generate", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) GenerateSpoofMetadata(ctx context.Context, in *clientpb.GenerateSpoofMetadataReq, opts ...grpc.CallOption) (*commonpb.Empty, error) {
	start := time.Now()
	resp, err := d.next.GenerateSpoofMetadata(ctx, in, opts...)
	d.hook.record(ctx, "GenerateSpoofMetadata", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) GenerateExternal(ctx context.Context, in *clientpb.ExternalGenerateReq, opts ...grpc.CallOption) (*clientpb.ExternalImplantConfig, error) {
	start := time.Now()
	resp, err := d.next.GenerateExternal(ctx, in, opts...)
	d.hook.record(ctx, "GenerateExternal", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) GenerateExternalSaveBuild(ctx context.Context, in *clientpb.ExternalImplantBinary, opts ...grpc.CallOption) (*commonpb.Empty, error) {
	start := time.Now()
	resp, err := d.next.GenerateExternalSaveBuild(ctx, in, opts...)
	d.hook.record(ctx, "GenerateExternalSaveBuild", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) GenerateExternalGetBuildConfig(ctx context.Context, in *clientpb.ImplantBuild, opts ...grpc.CallOption) (*clientpb.ExternalImplantConfig, error) {
	start := time.Now()
	resp, err := d.next.GenerateExternalGetBuildConfig(ctx, in, opts...)
	d.hook.record(ctx, "GenerateExternalGetBuildConfig", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) GenerateStage(ctx context.Context, in *clientpb.GenerateStageReq, opts ...grpc.CallOption) (*clientpb.Generate, error) {
	start := time.Now()
	resp, err := d.next.GenerateStage(ctx, in, opts...)
	d.hook.record(ctx, "GenerateStage", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) StageImplantBuild(ctx context.Context, in *clientpb.ImplantStageReq, opts ...grpc.CallOption) (*commonpb.Empty, error) {
	start := time.Now()
	resp, err := d.next.StageImplantBuild(ctx, in, opts...)
	d.hook.record(ctx, "StageImplantBuild", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) GetHTTPC2Profiles(ctx context.Context, in *commonpb.Empty, opts ...grpc.CallOption) (*clientpb.HTTPC2Configs, error) {
	start := time.Now()
	resp, err := d.next.GetHTTPC2Profiles(ctx, in, opts...)
	d.hook.record(ctx, "GetHTTPC2Profiles", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) GetHTTPC2ProfileByName(ctx context.Context, in *clientpb.C2ProfileReq, opts ...grpc.CallOption) (*clientpb.HTTPC2Config, error) {
	start := time.Now()
	resp, err := d.next.GetHTTPC2ProfileByName(ctx, in, opts...)
	d.hook.record(ctx, "GetHTTPC2ProfileByName", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) SaveHTTPC2Profile(ctx context.Context, in *clientpb.HTTPC2ConfigReq, opts ...grpc.CallOption) (*commonpb.Empty, error) {
	start := time.Now()
	resp, err := d.next.SaveHTTPC2Profile(ctx, in, opts...)
	d.hook.record(ctx, "SaveHTTPC2Profile", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) BuilderRegister(ctx context.Context, in *clientpb.Builder, opts ...grpc.CallOption) (rpcpb.SliverRPC_BuilderRegisterClient, error) {
	start := time.Now()
	stream, err := d.next.BuilderRegister(ctx, in, opts...)
	d.hook.record(ctx, "BuilderRegister", time.Since(start).Milliseconds(), err)
	return stream, err
}

func (d *journalDecorator) BuilderTrigger(ctx context.Context, in *clientpb.Event, opts ...grpc.CallOption) (*commonpb.Empty, error) {
	start := time.Now()
	resp, err := d.next.BuilderTrigger(ctx, in, opts...)
	d.hook.record(ctx, "BuilderTrigger", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) Builders(ctx context.Context, in *commonpb.Empty, opts ...grpc.CallOption) (*clientpb.Builders, error) {
	start := time.Now()
	resp, err := d.next.Builders(ctx, in, opts...)
	d.hook.record(ctx, "Builders", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) GetCertificateInfo(ctx context.Context, in *clientpb.CertificatesReq, opts ...grpc.CallOption) (*clientpb.CertificateInfo, error) {
	start := time.Now()
	resp, err := d.next.GetCertificateInfo(ctx, in, opts...)
	d.hook.record(ctx, "GetCertificateInfo", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) GetCertificateAuthorityInfo(ctx context.Context, in *commonpb.Empty, opts ...grpc.CallOption) (*clientpb.CertificateAuthorityInfo, error) {
	start := time.Now()
	resp, err := d.next.GetCertificateAuthorityInfo(ctx, in, opts...)
	d.hook.record(ctx, "GetCertificateAuthorityInfo", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) Crack(ctx context.Context, in *clientpb.CrackCommand, opts ...grpc.CallOption) (*clientpb.CrackResponse, error) {
	start := time.Now()
	resp, err := d.next.Crack(ctx, in, opts...)
	d.hook.record(ctx, "Crack", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) CrackstationRegister(ctx context.Context, in *clientpb.Crackstation, opts ...grpc.CallOption) (rpcpb.SliverRPC_CrackstationRegisterClient, error) {
	start := time.Now()
	stream, err := d.next.CrackstationRegister(ctx, in, opts...)
	d.hook.record(ctx, "CrackstationRegister", time.Since(start).Milliseconds(), err)
	return stream, err
}

func (d *journalDecorator) CrackstationTrigger(ctx context.Context, in *clientpb.Event, opts ...grpc.CallOption) (*commonpb.Empty, error) {
	start := time.Now()
	resp, err := d.next.CrackstationTrigger(ctx, in, opts...)
	d.hook.record(ctx, "CrackstationTrigger", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) CrackstationBenchmark(ctx context.Context, in *clientpb.CrackBenchmark, opts ...grpc.CallOption) (*commonpb.Empty, error) {
	start := time.Now()
	resp, err := d.next.CrackstationBenchmark(ctx, in, opts...)
	d.hook.record(ctx, "CrackstationBenchmark", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) Crackstations(ctx context.Context, in *commonpb.Empty, opts ...grpc.CallOption) (*clientpb.Crackstations, error) {
	start := time.Now()
	resp, err := d.next.Crackstations(ctx, in, opts...)
	d.hook.record(ctx, "Crackstations", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) CrackTaskByID(ctx context.Context, in *clientpb.CrackTask, opts ...grpc.CallOption) (*clientpb.CrackTask, error) {
	start := time.Now()
	resp, err := d.next.CrackTaskByID(ctx, in, opts...)
	d.hook.record(ctx, "CrackTaskByID", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) CrackTaskUpdate(ctx context.Context, in *clientpb.CrackTask, opts ...grpc.CallOption) (*commonpb.Empty, error) {
	start := time.Now()
	resp, err := d.next.CrackTaskUpdate(ctx, in, opts...)
	d.hook.record(ctx, "CrackTaskUpdate", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) CrackFilesList(ctx context.Context, in *clientpb.CrackFile, opts ...grpc.CallOption) (*clientpb.CrackFiles, error) {
	start := time.Now()
	resp, err := d.next.CrackFilesList(ctx, in, opts...)
	d.hook.record(ctx, "CrackFilesList", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) CrackFileCreate(ctx context.Context, in *clientpb.CrackFile, opts ...grpc.CallOption) (*clientpb.CrackFile, error) {
	start := time.Now()
	resp, err := d.next.CrackFileCreate(ctx, in, opts...)
	d.hook.record(ctx, "CrackFileCreate", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) CrackFileChunkUpload(ctx context.Context, in *clientpb.CrackFileChunk, opts ...grpc.CallOption) (*commonpb.Empty, error) {
	start := time.Now()
	resp, err := d.next.CrackFileChunkUpload(ctx, in, opts...)
	d.hook.record(ctx, "CrackFileChunkUpload", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) CrackFileChunkDownload(ctx context.Context, in *clientpb.CrackFileChunk, opts ...grpc.CallOption) (*clientpb.CrackFileChunk, error) {
	start := time.Now()
	resp, err := d.next.CrackFileChunkDownload(ctx, in, opts...)
	d.hook.record(ctx, "CrackFileChunkDownload", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) CrackFileComplete(ctx context.Context, in *clientpb.CrackFile, opts ...grpc.CallOption) (*commonpb.Empty, error) {
	start := time.Now()
	resp, err := d.next.CrackFileComplete(ctx, in, opts...)
	d.hook.record(ctx, "CrackFileComplete", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) CrackFileDelete(ctx context.Context, in *clientpb.CrackFile, opts ...grpc.CallOption) (*commonpb.Empty, error) {
	start := time.Now()
	resp, err := d.next.CrackFileDelete(ctx, in, opts...)
	d.hook.record(ctx, "CrackFileDelete", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) Regenerate(ctx context.Context, in *clientpb.RegenerateReq, opts ...grpc.CallOption) (*clientpb.Generate, error) {
	start := time.Now()
	resp, err := d.next.Regenerate(ctx, in, opts...)
	d.hook.record(ctx, "Regenerate", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) ImplantBuilds(ctx context.Context, in *commonpb.Empty, opts ...grpc.CallOption) (*clientpb.ImplantBuilds, error) {
	start := time.Now()
	resp, err := d.next.ImplantBuilds(ctx, in, opts...)
	d.hook.record(ctx, "ImplantBuilds", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) DeleteImplantBuild(ctx context.Context, in *clientpb.DeleteReq, opts ...grpc.CallOption) (*commonpb.Empty, error) {
	start := time.Now()
	resp, err := d.next.DeleteImplantBuild(ctx, in, opts...)
	d.hook.record(ctx, "DeleteImplantBuild", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) Canaries(ctx context.Context, in *commonpb.Empty, opts ...grpc.CallOption) (*clientpb.Canaries, error) {
	start := time.Now()
	resp, err := d.next.Canaries(ctx, in, opts...)
	d.hook.record(ctx, "Canaries", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) GenerateWGClientConfig(ctx context.Context, in *commonpb.Empty, opts ...grpc.CallOption) (*clientpb.WGClientConfig, error) {
	start := time.Now()
	resp, err := d.next.GenerateWGClientConfig(ctx, in, opts...)
	d.hook.record(ctx, "GenerateWGClientConfig", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) GenerateUniqueIP(ctx context.Context, in *commonpb.Empty, opts ...grpc.CallOption) (*clientpb.UniqueWGIP, error) {
	start := time.Now()
	resp, err := d.next.GenerateUniqueIP(ctx, in, opts...)
	d.hook.record(ctx, "GenerateUniqueIP", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) ImplantProfiles(ctx context.Context, in *commonpb.Empty, opts ...grpc.CallOption) (*clientpb.ImplantProfiles, error) {
	start := time.Now()
	resp, err := d.next.ImplantProfiles(ctx, in, opts...)
	d.hook.record(ctx, "ImplantProfiles", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) DeleteImplantProfile(ctx context.Context, in *clientpb.DeleteReq, opts ...grpc.CallOption) (*commonpb.Empty, error) {
	start := time.Now()
	resp, err := d.next.DeleteImplantProfile(ctx, in, opts...)
	d.hook.record(ctx, "DeleteImplantProfile", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) SaveImplantProfile(ctx context.Context, in *clientpb.ImplantProfile, opts ...grpc.CallOption) (*clientpb.ImplantProfile, error) {
	start := time.Now()
	resp, err := d.next.SaveImplantProfile(ctx, in, opts...)
	d.hook.record(ctx, "SaveImplantProfile", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) ShellcodeRDI(ctx context.Context, in *clientpb.ShellcodeRDIReq, opts ...grpc.CallOption) (*clientpb.ShellcodeRDI, error) {
	start := time.Now()
	resp, err := d.next.ShellcodeRDI(ctx, in, opts...)
	d.hook.record(ctx, "ShellcodeRDI", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) GetCompiler(ctx context.Context, in *commonpb.Empty, opts ...grpc.CallOption) (*clientpb.Compiler, error) {
	start := time.Now()
	resp, err := d.next.GetCompiler(ctx, in, opts...)
	d.hook.record(ctx, "GetCompiler", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) ShellcodeEncoder(ctx context.Context, in *clientpb.ShellcodeEncodeReq, opts ...grpc.CallOption) (*clientpb.ShellcodeEncode, error) {
	start := time.Now()
	resp, err := d.next.ShellcodeEncoder(ctx, in, opts...)
	d.hook.record(ctx, "ShellcodeEncoder", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) ShellcodeEncoderMap(ctx context.Context, in *commonpb.Empty, opts ...grpc.CallOption) (*clientpb.ShellcodeEncoderMap, error) {
	start := time.Now()
	resp, err := d.next.ShellcodeEncoderMap(ctx, in, opts...)
	d.hook.record(ctx, "ShellcodeEncoderMap", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) TrafficEncoderMap(ctx context.Context, in *commonpb.Empty, opts ...grpc.CallOption) (*clientpb.TrafficEncoderMap, error) {
	start := time.Now()
	resp, err := d.next.TrafficEncoderMap(ctx, in, opts...)
	d.hook.record(ctx, "TrafficEncoderMap", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) TrafficEncoderAdd(ctx context.Context, in *clientpb.TrafficEncoder, opts ...grpc.CallOption) (*clientpb.TrafficEncoderTests, error) {
	start := time.Now()
	resp, err := d.next.TrafficEncoderAdd(ctx, in, opts...)
	d.hook.record(ctx, "TrafficEncoderAdd", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) TrafficEncoderRm(ctx context.Context, in *clientpb.TrafficEncoder, opts ...grpc.CallOption) (*commonpb.Empty, error) {
	start := time.Now()
	resp, err := d.next.TrafficEncoderRm(ctx, in, opts...)
	d.hook.record(ctx, "TrafficEncoderRm", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) Websites(ctx context.Context, in *commonpb.Empty, opts ...grpc.CallOption) (*clientpb.Websites, error) {
	start := time.Now()
	resp, err := d.next.Websites(ctx, in, opts...)
	d.hook.record(ctx, "Websites", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) Website(ctx context.Context, in *clientpb.Website, opts ...grpc.CallOption) (*clientpb.Website, error) {
	start := time.Now()
	resp, err := d.next.Website(ctx, in, opts...)
	d.hook.record(ctx, "Website", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) WebsiteRemove(ctx context.Context, in *clientpb.Website, opts ...grpc.CallOption) (*commonpb.Empty, error) {
	start := time.Now()
	resp, err := d.next.WebsiteRemove(ctx, in, opts...)
	d.hook.record(ctx, "WebsiteRemove", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) WebsiteAddContent(ctx context.Context, in *clientpb.WebsiteAddContent, opts ...grpc.CallOption) (*clientpb.Website, error) {
	start := time.Now()
	resp, err := d.next.WebsiteAddContent(ctx, in, opts...)
	d.hook.record(ctx, "WebsiteAddContent", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) WebsiteUpdateContent(ctx context.Context, in *clientpb.WebsiteAddContent, opts ...grpc.CallOption) (*clientpb.Website, error) {
	start := time.Now()
	resp, err := d.next.WebsiteUpdateContent(ctx, in, opts...)
	d.hook.record(ctx, "WebsiteUpdateContent", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) WebsiteRemoveContent(ctx context.Context, in *clientpb.WebsiteRemoveContent, opts ...grpc.CallOption) (*clientpb.Website, error) {
	start := time.Now()
	resp, err := d.next.WebsiteRemoveContent(ctx, in, opts...)
	d.hook.record(ctx, "WebsiteRemoveContent", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) Ping(ctx context.Context, in *sliverpb.Ping, opts ...grpc.CallOption) (*sliverpb.Ping, error) {
	start := time.Now()
	resp, err := d.next.Ping(ctx, in, opts...)
	d.hook.record(ctx, "Ping", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) Ps(ctx context.Context, in *sliverpb.PsReq, opts ...grpc.CallOption) (*sliverpb.Ps, error) {
	start := time.Now()
	resp, err := d.next.Ps(ctx, in, opts...)
	d.hook.record(ctx, "Ps", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) Terminate(ctx context.Context, in *sliverpb.TerminateReq, opts ...grpc.CallOption) (*sliverpb.Terminate, error) {
	start := time.Now()
	resp, err := d.next.Terminate(ctx, in, opts...)
	d.hook.record(ctx, "Terminate", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) Ifconfig(ctx context.Context, in *sliverpb.IfconfigReq, opts ...grpc.CallOption) (*sliverpb.Ifconfig, error) {
	start := time.Now()
	resp, err := d.next.Ifconfig(ctx, in, opts...)
	d.hook.record(ctx, "Ifconfig", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) Netstat(ctx context.Context, in *sliverpb.NetstatReq, opts ...grpc.CallOption) (*sliverpb.Netstat, error) {
	start := time.Now()
	resp, err := d.next.Netstat(ctx, in, opts...)
	d.hook.record(ctx, "Netstat", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) Ls(ctx context.Context, in *sliverpb.LsReq, opts ...grpc.CallOption) (*sliverpb.Ls, error) {
	start := time.Now()
	resp, err := d.next.Ls(ctx, in, opts...)
	d.hook.record(ctx, "Ls", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) Cd(ctx context.Context, in *sliverpb.CdReq, opts ...grpc.CallOption) (*sliverpb.Pwd, error) {
	start := time.Now()
	resp, err := d.next.Cd(ctx, in, opts...)
	d.hook.record(ctx, "Cd", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) Pwd(ctx context.Context, in *sliverpb.PwdReq, opts ...grpc.CallOption) (*sliverpb.Pwd, error) {
	start := time.Now()
	resp, err := d.next.Pwd(ctx, in, opts...)
	d.hook.record(ctx, "Pwd", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) Mv(ctx context.Context, in *sliverpb.MvReq, opts ...grpc.CallOption) (*sliverpb.Mv, error) {
	start := time.Now()
	resp, err := d.next.Mv(ctx, in, opts...)
	d.hook.record(ctx, "Mv", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) Cp(ctx context.Context, in *sliverpb.CpReq, opts ...grpc.CallOption) (*sliverpb.Cp, error) {
	start := time.Now()
	resp, err := d.next.Cp(ctx, in, opts...)
	d.hook.record(ctx, "Cp", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) Rm(ctx context.Context, in *sliverpb.RmReq, opts ...grpc.CallOption) (*sliverpb.Rm, error) {
	start := time.Now()
	resp, err := d.next.Rm(ctx, in, opts...)
	d.hook.record(ctx, "Rm", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) Mkdir(ctx context.Context, in *sliverpb.MkdirReq, opts ...grpc.CallOption) (*sliverpb.Mkdir, error) {
	start := time.Now()
	resp, err := d.next.Mkdir(ctx, in, opts...)
	d.hook.record(ctx, "Mkdir", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) Download(ctx context.Context, in *sliverpb.DownloadReq, opts ...grpc.CallOption) (*sliverpb.Download, error) {
	start := time.Now()
	resp, err := d.next.Download(ctx, in, opts...)
	d.hook.record(ctx, "Download", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) Upload(ctx context.Context, in *sliverpb.UploadReq, opts ...grpc.CallOption) (*sliverpb.Upload, error) {
	start := time.Now()
	resp, err := d.next.Upload(ctx, in, opts...)
	d.hook.record(ctx, "Upload", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) Grep(ctx context.Context, in *sliverpb.GrepReq, opts ...grpc.CallOption) (*sliverpb.Grep, error) {
	start := time.Now()
	resp, err := d.next.Grep(ctx, in, opts...)
	d.hook.record(ctx, "Grep", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) Chmod(ctx context.Context, in *sliverpb.ChmodReq, opts ...grpc.CallOption) (*sliverpb.Chmod, error) {
	start := time.Now()
	resp, err := d.next.Chmod(ctx, in, opts...)
	d.hook.record(ctx, "Chmod", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) Chown(ctx context.Context, in *sliverpb.ChownReq, opts ...grpc.CallOption) (*sliverpb.Chown, error) {
	start := time.Now()
	resp, err := d.next.Chown(ctx, in, opts...)
	d.hook.record(ctx, "Chown", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) Chtimes(ctx context.Context, in *sliverpb.ChtimesReq, opts ...grpc.CallOption) (*sliverpb.Chtimes, error) {
	start := time.Now()
	resp, err := d.next.Chtimes(ctx, in, opts...)
	d.hook.record(ctx, "Chtimes", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) MemfilesList(ctx context.Context, in *sliverpb.MemfilesListReq, opts ...grpc.CallOption) (*sliverpb.Ls, error) {
	start := time.Now()
	resp, err := d.next.MemfilesList(ctx, in, opts...)
	d.hook.record(ctx, "MemfilesList", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) MemfilesAdd(ctx context.Context, in *sliverpb.MemfilesAddReq, opts ...grpc.CallOption) (*sliverpb.MemfilesAdd, error) {
	start := time.Now()
	resp, err := d.next.MemfilesAdd(ctx, in, opts...)
	d.hook.record(ctx, "MemfilesAdd", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) MemfilesRm(ctx context.Context, in *sliverpb.MemfilesRmReq, opts ...grpc.CallOption) (*sliverpb.MemfilesRm, error) {
	start := time.Now()
	resp, err := d.next.MemfilesRm(ctx, in, opts...)
	d.hook.record(ctx, "MemfilesRm", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) Mount(ctx context.Context, in *sliverpb.MountReq, opts ...grpc.CallOption) (*sliverpb.Mount, error) {
	start := time.Now()
	resp, err := d.next.Mount(ctx, in, opts...)
	d.hook.record(ctx, "Mount", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) ProcessDump(ctx context.Context, in *sliverpb.ProcessDumpReq, opts ...grpc.CallOption) (*sliverpb.ProcessDump, error) {
	start := time.Now()
	resp, err := d.next.ProcessDump(ctx, in, opts...)
	d.hook.record(ctx, "ProcessDump", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) RunAs(ctx context.Context, in *sliverpb.RunAsReq, opts ...grpc.CallOption) (*sliverpb.RunAs, error) {
	start := time.Now()
	resp, err := d.next.RunAs(ctx, in, opts...)
	d.hook.record(ctx, "RunAs", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) Impersonate(ctx context.Context, in *sliverpb.ImpersonateReq, opts ...grpc.CallOption) (*sliverpb.Impersonate, error) {
	start := time.Now()
	resp, err := d.next.Impersonate(ctx, in, opts...)
	d.hook.record(ctx, "Impersonate", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) RevToSelf(ctx context.Context, in *sliverpb.RevToSelfReq, opts ...grpc.CallOption) (*sliverpb.RevToSelf, error) {
	start := time.Now()
	resp, err := d.next.RevToSelf(ctx, in, opts...)
	d.hook.record(ctx, "RevToSelf", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) GetSystem(ctx context.Context, in *clientpb.GetSystemReq, opts ...grpc.CallOption) (*sliverpb.GetSystem, error) {
	start := time.Now()
	resp, err := d.next.GetSystem(ctx, in, opts...)
	d.hook.record(ctx, "GetSystem", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) Task(ctx context.Context, in *sliverpb.TaskReq, opts ...grpc.CallOption) (*sliverpb.Task, error) {
	start := time.Now()
	resp, err := d.next.Task(ctx, in, opts...)
	d.hook.record(ctx, "Task", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) Msf(ctx context.Context, in *clientpb.MSFReq, opts ...grpc.CallOption) (*sliverpb.Task, error) {
	start := time.Now()
	resp, err := d.next.Msf(ctx, in, opts...)
	d.hook.record(ctx, "Msf", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) MsfRemote(ctx context.Context, in *clientpb.MSFRemoteReq, opts ...grpc.CallOption) (*sliverpb.Task, error) {
	start := time.Now()
	resp, err := d.next.MsfRemote(ctx, in, opts...)
	d.hook.record(ctx, "MsfRemote", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) ExecuteAssembly(ctx context.Context, in *sliverpb.ExecuteAssemblyReq, opts ...grpc.CallOption) (*sliverpb.ExecuteAssembly, error) {
	start := time.Now()
	resp, err := d.next.ExecuteAssembly(ctx, in, opts...)
	d.hook.record(ctx, "ExecuteAssembly", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) Migrate(ctx context.Context, in *clientpb.MigrateReq, opts ...grpc.CallOption) (*sliverpb.Migrate, error) {
	start := time.Now()
	resp, err := d.next.Migrate(ctx, in, opts...)
	d.hook.record(ctx, "Migrate", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) Execute(ctx context.Context, in *sliverpb.ExecuteReq, opts ...grpc.CallOption) (*sliverpb.Execute, error) {
	start := time.Now()
	resp, err := d.next.Execute(ctx, in, opts...)
	d.hook.record(ctx, "Execute", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) ExecuteWindows(ctx context.Context, in *sliverpb.ExecuteWindowsReq, opts ...grpc.CallOption) (*sliverpb.Execute, error) {
	start := time.Now()
	resp, err := d.next.ExecuteWindows(ctx, in, opts...)
	d.hook.record(ctx, "ExecuteWindows", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) ExecuteChildren(ctx context.Context, in *sliverpb.ExecuteChildrenReq, opts ...grpc.CallOption) (*sliverpb.ExecuteChildren, error) {
	start := time.Now()
	resp, err := d.next.ExecuteChildren(ctx, in, opts...)
	d.hook.record(ctx, "ExecuteChildren", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) Sideload(ctx context.Context, in *sliverpb.SideloadReq, opts ...grpc.CallOption) (*sliverpb.Sideload, error) {
	start := time.Now()
	resp, err := d.next.Sideload(ctx, in, opts...)
	d.hook.record(ctx, "Sideload", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) SpawnDll(ctx context.Context, in *sliverpb.InvokeSpawnDllReq, opts ...grpc.CallOption) (*sliverpb.SpawnDll, error) {
	start := time.Now()
	resp, err := d.next.SpawnDll(ctx, in, opts...)
	d.hook.record(ctx, "SpawnDll", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) Screenshot(ctx context.Context, in *sliverpb.ScreenshotReq, opts ...grpc.CallOption) (*sliverpb.Screenshot, error) {
	start := time.Now()
	resp, err := d.next.Screenshot(ctx, in, opts...)
	d.hook.record(ctx, "Screenshot", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) CurrentTokenOwner(ctx context.Context, in *sliverpb.CurrentTokenOwnerReq, opts ...grpc.CallOption) (*sliverpb.CurrentTokenOwner, error) {
	start := time.Now()
	resp, err := d.next.CurrentTokenOwner(ctx, in, opts...)
	d.hook.record(ctx, "CurrentTokenOwner", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) Services(ctx context.Context, in *sliverpb.ServicesReq, opts ...grpc.CallOption) (*sliverpb.Services, error) {
	start := time.Now()
	resp, err := d.next.Services(ctx, in, opts...)
	d.hook.record(ctx, "Services", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) ServiceDetail(ctx context.Context, in *sliverpb.ServiceDetailReq, opts ...grpc.CallOption) (*sliverpb.ServiceDetail, error) {
	start := time.Now()
	resp, err := d.next.ServiceDetail(ctx, in, opts...)
	d.hook.record(ctx, "ServiceDetail", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) StartServiceByName(ctx context.Context, in *sliverpb.StartServiceByNameReq, opts ...grpc.CallOption) (*sliverpb.ServiceInfo, error) {
	start := time.Now()
	resp, err := d.next.StartServiceByName(ctx, in, opts...)
	d.hook.record(ctx, "StartServiceByName", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) PivotStartListener(ctx context.Context, in *sliverpb.PivotStartListenerReq, opts ...grpc.CallOption) (*sliverpb.PivotListener, error) {
	start := time.Now()
	resp, err := d.next.PivotStartListener(ctx, in, opts...)
	d.hook.record(ctx, "PivotStartListener", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) PivotStopListener(ctx context.Context, in *sliverpb.PivotStopListenerReq, opts ...grpc.CallOption) (*commonpb.Empty, error) {
	start := time.Now()
	resp, err := d.next.PivotStopListener(ctx, in, opts...)
	d.hook.record(ctx, "PivotStopListener", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) PivotSessionListeners(ctx context.Context, in *sliverpb.PivotListenersReq, opts ...grpc.CallOption) (*sliverpb.PivotListeners, error) {
	start := time.Now()
	resp, err := d.next.PivotSessionListeners(ctx, in, opts...)
	d.hook.record(ctx, "PivotSessionListeners", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) PivotGraph(ctx context.Context, in *commonpb.Empty, opts ...grpc.CallOption) (*clientpb.PivotGraph, error) {
	start := time.Now()
	resp, err := d.next.PivotGraph(ctx, in, opts...)
	d.hook.record(ctx, "PivotGraph", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) StartService(ctx context.Context, in *sliverpb.StartServiceReq, opts ...grpc.CallOption) (*sliverpb.ServiceInfo, error) {
	start := time.Now()
	resp, err := d.next.StartService(ctx, in, opts...)
	d.hook.record(ctx, "StartService", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) StopService(ctx context.Context, in *sliverpb.StopServiceReq, opts ...grpc.CallOption) (*sliverpb.ServiceInfo, error) {
	start := time.Now()
	resp, err := d.next.StopService(ctx, in, opts...)
	d.hook.record(ctx, "StopService", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) RemoveService(ctx context.Context, in *sliverpb.RemoveServiceReq, opts ...grpc.CallOption) (*sliverpb.ServiceInfo, error) {
	start := time.Now()
	resp, err := d.next.RemoveService(ctx, in, opts...)
	d.hook.record(ctx, "RemoveService", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) MakeToken(ctx context.Context, in *sliverpb.MakeTokenReq, opts ...grpc.CallOption) (*sliverpb.MakeToken, error) {
	start := time.Now()
	resp, err := d.next.MakeToken(ctx, in, opts...)
	d.hook.record(ctx, "MakeToken", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) GetEnv(ctx context.Context, in *sliverpb.EnvReq, opts ...grpc.CallOption) (*sliverpb.EnvInfo, error) {
	start := time.Now()
	resp, err := d.next.GetEnv(ctx, in, opts...)
	d.hook.record(ctx, "GetEnv", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) SetEnv(ctx context.Context, in *sliverpb.SetEnvReq, opts ...grpc.CallOption) (*sliverpb.SetEnv, error) {
	start := time.Now()
	resp, err := d.next.SetEnv(ctx, in, opts...)
	d.hook.record(ctx, "SetEnv", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) UnsetEnv(ctx context.Context, in *sliverpb.UnsetEnvReq, opts ...grpc.CallOption) (*sliverpb.UnsetEnv, error) {
	start := time.Now()
	resp, err := d.next.UnsetEnv(ctx, in, opts...)
	d.hook.record(ctx, "UnsetEnv", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) Backdoor(ctx context.Context, in *clientpb.BackdoorReq, opts ...grpc.CallOption) (*clientpb.Backdoor, error) {
	start := time.Now()
	resp, err := d.next.Backdoor(ctx, in, opts...)
	d.hook.record(ctx, "Backdoor", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) RegistryRead(ctx context.Context, in *sliverpb.RegistryReadReq, opts ...grpc.CallOption) (*sliverpb.RegistryRead, error) {
	start := time.Now()
	resp, err := d.next.RegistryRead(ctx, in, opts...)
	d.hook.record(ctx, "RegistryRead", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) RegistryWrite(ctx context.Context, in *sliverpb.RegistryWriteReq, opts ...grpc.CallOption) (*sliverpb.RegistryWrite, error) {
	start := time.Now()
	resp, err := d.next.RegistryWrite(ctx, in, opts...)
	d.hook.record(ctx, "RegistryWrite", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) RegistryCreateKey(ctx context.Context, in *sliverpb.RegistryCreateKeyReq, opts ...grpc.CallOption) (*sliverpb.RegistryCreateKey, error) {
	start := time.Now()
	resp, err := d.next.RegistryCreateKey(ctx, in, opts...)
	d.hook.record(ctx, "RegistryCreateKey", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) RegistryDeleteKey(ctx context.Context, in *sliverpb.RegistryDeleteKeyReq, opts ...grpc.CallOption) (*sliverpb.RegistryDeleteKey, error) {
	start := time.Now()
	resp, err := d.next.RegistryDeleteKey(ctx, in, opts...)
	d.hook.record(ctx, "RegistryDeleteKey", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) RegistryListSubKeys(ctx context.Context, in *sliverpb.RegistrySubKeyListReq, opts ...grpc.CallOption) (*sliverpb.RegistrySubKeyList, error) {
	start := time.Now()
	resp, err := d.next.RegistryListSubKeys(ctx, in, opts...)
	d.hook.record(ctx, "RegistryListSubKeys", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) RegistryListValues(ctx context.Context, in *sliverpb.RegistryListValuesReq, opts ...grpc.CallOption) (*sliverpb.RegistryValuesList, error) {
	start := time.Now()
	resp, err := d.next.RegistryListValues(ctx, in, opts...)
	d.hook.record(ctx, "RegistryListValues", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) RegistryReadHive(ctx context.Context, in *sliverpb.RegistryReadHiveReq, opts ...grpc.CallOption) (*sliverpb.RegistryReadHive, error) {
	start := time.Now()
	resp, err := d.next.RegistryReadHive(ctx, in, opts...)
	d.hook.record(ctx, "RegistryReadHive", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) RunSSHCommand(ctx context.Context, in *sliverpb.SSHCommandReq, opts ...grpc.CallOption) (*sliverpb.SSHCommand, error) {
	start := time.Now()
	resp, err := d.next.RunSSHCommand(ctx, in, opts...)
	d.hook.record(ctx, "RunSSHCommand", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) HijackDLL(ctx context.Context, in *clientpb.DllHijackReq, opts ...grpc.CallOption) (*clientpb.DllHijack, error) {
	start := time.Now()
	resp, err := d.next.HijackDLL(ctx, in, opts...)
	d.hook.record(ctx, "HijackDLL", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) GetPrivs(ctx context.Context, in *sliverpb.GetPrivsReq, opts ...grpc.CallOption) (*sliverpb.GetPrivs, error) {
	start := time.Now()
	resp, err := d.next.GetPrivs(ctx, in, opts...)
	d.hook.record(ctx, "GetPrivs", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) StartRportFwdListener(ctx context.Context, in *sliverpb.RportFwdStartListenerReq, opts ...grpc.CallOption) (*sliverpb.RportFwdListener, error) {
	start := time.Now()
	resp, err := d.next.StartRportFwdListener(ctx, in, opts...)
	d.hook.record(ctx, "StartRportFwdListener", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) GetRportFwdListeners(ctx context.Context, in *sliverpb.RportFwdListenersReq, opts ...grpc.CallOption) (*sliverpb.RportFwdListeners, error) {
	start := time.Now()
	resp, err := d.next.GetRportFwdListeners(ctx, in, opts...)
	d.hook.record(ctx, "GetRportFwdListeners", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) StopRportFwdListener(ctx context.Context, in *sliverpb.RportFwdStopListenerReq, opts ...grpc.CallOption) (*sliverpb.RportFwdListener, error) {
	start := time.Now()
	resp, err := d.next.StopRportFwdListener(ctx, in, opts...)
	d.hook.record(ctx, "StopRportFwdListener", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) OpenSession(ctx context.Context, in *sliverpb.OpenSession, opts ...grpc.CallOption) (*sliverpb.OpenSession, error) {
	start := time.Now()
	resp, err := d.next.OpenSession(ctx, in, opts...)
	d.hook.record(ctx, "OpenSession", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) CloseSession(ctx context.Context, in *sliverpb.CloseSession, opts ...grpc.CallOption) (*commonpb.Empty, error) {
	start := time.Now()
	resp, err := d.next.CloseSession(ctx, in, opts...)
	d.hook.record(ctx, "CloseSession", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) RegisterExtension(ctx context.Context, in *sliverpb.RegisterExtensionReq, opts ...grpc.CallOption) (*sliverpb.RegisterExtension, error) {
	start := time.Now()
	resp, err := d.next.RegisterExtension(ctx, in, opts...)
	d.hook.record(ctx, "RegisterExtension", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) CallExtension(ctx context.Context, in *sliverpb.CallExtensionReq, opts ...grpc.CallOption) (*sliverpb.CallExtension, error) {
	start := time.Now()
	resp, err := d.next.CallExtension(ctx, in, opts...)
	d.hook.record(ctx, "CallExtension", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) ListExtensions(ctx context.Context, in *sliverpb.ListExtensionsReq, opts ...grpc.CallOption) (*sliverpb.ListExtensions, error) {
	start := time.Now()
	resp, err := d.next.ListExtensions(ctx, in, opts...)
	d.hook.record(ctx, "ListExtensions", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) RegisterWasmExtension(ctx context.Context, in *sliverpb.RegisterWasmExtensionReq, opts ...grpc.CallOption) (*sliverpb.RegisterWasmExtension, error) {
	start := time.Now()
	resp, err := d.next.RegisterWasmExtension(ctx, in, opts...)
	d.hook.record(ctx, "RegisterWasmExtension", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) ListWasmExtensions(ctx context.Context, in *sliverpb.ListWasmExtensionsReq, opts ...grpc.CallOption) (*sliverpb.ListWasmExtensions, error) {
	start := time.Now()
	resp, err := d.next.ListWasmExtensions(ctx, in, opts...)
	d.hook.record(ctx, "ListWasmExtensions", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) ExecWasmExtension(ctx context.Context, in *sliverpb.ExecWasmExtensionReq, opts ...grpc.CallOption) (*sliverpb.ExecWasmExtension, error) {
	start := time.Now()
	resp, err := d.next.ExecWasmExtension(ctx, in, opts...)
	d.hook.record(ctx, "ExecWasmExtension", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) WGStartPortForward(ctx context.Context, in *sliverpb.WGPortForwardStartReq, opts ...grpc.CallOption) (*sliverpb.WGPortForward, error) {
	start := time.Now()
	resp, err := d.next.WGStartPortForward(ctx, in, opts...)
	d.hook.record(ctx, "WGStartPortForward", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) WGStopPortForward(ctx context.Context, in *sliverpb.WGPortForwardStopReq, opts ...grpc.CallOption) (*sliverpb.WGPortForward, error) {
	start := time.Now()
	resp, err := d.next.WGStopPortForward(ctx, in, opts...)
	d.hook.record(ctx, "WGStopPortForward", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) WGStartSocks(ctx context.Context, in *sliverpb.WGSocksStartReq, opts ...grpc.CallOption) (*sliverpb.WGSocks, error) {
	start := time.Now()
	resp, err := d.next.WGStartSocks(ctx, in, opts...)
	d.hook.record(ctx, "WGStartSocks", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) WGStopSocks(ctx context.Context, in *sliverpb.WGSocksStopReq, opts ...grpc.CallOption) (*sliverpb.WGSocks, error) {
	start := time.Now()
	resp, err := d.next.WGStopSocks(ctx, in, opts...)
	d.hook.record(ctx, "WGStopSocks", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) WGListForwarders(ctx context.Context, in *sliverpb.WGTCPForwardersReq, opts ...grpc.CallOption) (*sliverpb.WGTCPForwarders, error) {
	start := time.Now()
	resp, err := d.next.WGListForwarders(ctx, in, opts...)
	d.hook.record(ctx, "WGListForwarders", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) WGListSocksServers(ctx context.Context, in *sliverpb.WGSocksServersReq, opts ...grpc.CallOption) (*sliverpb.WGSocksServers, error) {
	start := time.Now()
	resp, err := d.next.WGListSocksServers(ctx, in, opts...)
	d.hook.record(ctx, "WGListSocksServers", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) Shell(ctx context.Context, in *sliverpb.ShellReq, opts ...grpc.CallOption) (*sliverpb.Shell, error) {
	start := time.Now()
	resp, err := d.next.Shell(ctx, in, opts...)
	d.hook.record(ctx, "Shell", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) ShellResize(ctx context.Context, in *sliverpb.ShellResizeReq, opts ...grpc.CallOption) (*commonpb.Empty, error) {
	start := time.Now()
	resp, err := d.next.ShellResize(ctx, in, opts...)
	d.hook.record(ctx, "ShellResize", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) Portfwd(ctx context.Context, in *sliverpb.PortfwdReq, opts ...grpc.CallOption) (*sliverpb.Portfwd, error) {
	start := time.Now()
	resp, err := d.next.Portfwd(ctx, in, opts...)
	d.hook.record(ctx, "Portfwd", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) CreateSocks(ctx context.Context, in *sliverpb.Socks, opts ...grpc.CallOption) (*sliverpb.Socks, error) {
	start := time.Now()
	resp, err := d.next.CreateSocks(ctx, in, opts...)
	d.hook.record(ctx, "CreateSocks", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) CloseSocks(ctx context.Context, in *sliverpb.Socks, opts ...grpc.CallOption) (*commonpb.Empty, error) {
	start := time.Now()
	resp, err := d.next.CloseSocks(ctx, in, opts...)
	d.hook.record(ctx, "CloseSocks", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) SocksProxy(ctx context.Context, opts ...grpc.CallOption) (rpcpb.SliverRPC_SocksProxyClient, error) {
	start := time.Now()
	stream, err := d.next.SocksProxy(ctx, opts...)
	d.hook.record(ctx, "SocksProxy", time.Since(start).Milliseconds(), err)
	return stream, err
}

func (d *journalDecorator) CreateTunnel(ctx context.Context, in *sliverpb.Tunnel, opts ...grpc.CallOption) (*sliverpb.Tunnel, error) {
	start := time.Now()
	resp, err := d.next.CreateTunnel(ctx, in, opts...)
	d.hook.record(ctx, "CreateTunnel", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) CloseTunnel(ctx context.Context, in *sliverpb.Tunnel, opts ...grpc.CallOption) (*commonpb.Empty, error) {
	start := time.Now()
	resp, err := d.next.CloseTunnel(ctx, in, opts...)
	d.hook.record(ctx, "CloseTunnel", time.Since(start).Milliseconds(), err)
	return resp, err
}

func (d *journalDecorator) TunnelData(ctx context.Context, opts ...grpc.CallOption) (rpcpb.SliverRPC_TunnelDataClient, error) {
	start := time.Now()
	stream, err := d.next.TunnelData(ctx, opts...)
	d.hook.record(ctx, "TunnelData", time.Since(start).Milliseconds(), err)
	return stream, err
}

func (d *journalDecorator) Events(ctx context.Context, in *commonpb.Empty, opts ...grpc.CallOption) (rpcpb.SliverRPC_EventsClient, error) {
	start := time.Now()
	stream, err := d.next.Events(ctx, in, opts...)
	d.hook.record(ctx, "Events", time.Since(start).Milliseconds(), err)
	return stream, err
}
